spring.application.name=hoser_backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/hoser?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=dGFsZW50YnJpZGdlc2VjcmV0a2V5Zm9yandiYXNlNjRlbmNvZGVkc3RyaW5nMTIzNDU2Nzg5MA==
app.jwt.expiration-ms=86400000

app.admin.seed.enabled=${ADMIN_SEED_ENABLED:true}
app.admin.seed.username=${ADMIN_SEED_USERNAME:admin}
app.admin.seed.email=${ADMIN_SEED_EMAIL:admin@example.local}
app.admin.seed.password=${ADMIN_SEED_PASSWORD:Admin12345!}
app.payment.callback-token=${PAYMENT_CALLBACK_TOKEN:dev-callback-token}

logging.level.com.minhthien.web.hoser=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dzfgq2n19}
cloudinary.api-key=${CLOUDINARY_API_KEY:922436613794848}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:08Xv8-w4q0AH9IPY1PdpMhA5TKA}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minhthieen0@gmail.com
spring.mail.password=lewijhmkwqfyhzfz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

google.client-id=798255039135-0o8kh6bhfq33qkjehg87d8q7uav28tf7.apps.googleusercontent.com

facebook.app-id=26103012215974574
facebook.app-secret=868028ffa68aaad2589e459881bf003c

zalopay.app-id=2554
zalopay.key1=sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn
zalopay.key2=trMrHtvjo6myautxDUiAcYsVtaeQ8nhf
zalopay.create-url=https://sb-openapi.zalopay.vn/v2/create
zalopay.query-url=https://sb-openapi.zalopay.vn/v2/query
app.public-url=http://localhost:8080
zalopay.redirect-url= https://nonportable-overlusciously-silvia.ngrok-free.dev/api/zalopay/return
zalopay.callback-url= https://nonportable-overlusciously-silvia.ngrok-free.dev/api/zalopay/callback
